[package]
name = "traits"
version = "0.1.0"
edition = "2021"

[lib]
name = "aggregator"
path = "src/aggregator/lib.rs"

[[bin]]
name = "traits"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
